# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 503416a5d0d1cf218df277ce2ddf7a4c2e3188e7a86e0c7b7bc7168646db0517fd23c537bdfa7fd3c2f33b3b6ce2c2b0237328abd7ce3f839166ac9983e14323

test:
  secret_key_base: f7252cc4270702462b0a24afe06a51f6ae4f195fce5e84ac0902d11621f23f7df943fce3ce229360dd561c5bea3ab4028ccf4beb73d15c187470377f4c62bff0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
